### ISSUE TITLE
Underscores not working as expected on binary and hexadecimal numbers

### ISSUE THREAD

**Issue by ewd3v** [seaofvoices/darklua#102]
In Luau, numbers like these are valid:
```lua
print(0_b11)
print(0_x0101)
```

But when Darklua parses this code, it throws an error. It still accepts numbers like these:
```lua
print(0b_11)
print(0x_0101)
print(1_e3) -- Works on exponents?
print(1e_3)
```

**Comment by jeparlefrancais** [comment]
Thank you for reporting the issue! There is existing logic to filter the underscores when parsing a number but I see that it happens _after_ checking if the number starts with `0x` or `0b` (see the [implementation](https://github.com/seaofvoices/darklua/blob/main/src/nodes/expressions/number.rs#L344)). It will be an easy fix 🙂

**Comment by bainchild** [comment]
This also happens with decimal numbers where there is an underscore after the point but before any numbers after the point.
![image](https://github.com/seaofvoices/darklua/assets/55368789/7f820203-9863-4189-ada6-6a5035e19fb8)
