### ISSUE TITLE
Luau supports underscores immediately after the decimal point.

### ISSUE THREAD

**Issue by bainchild** [seaofvoices/darklua#105]
`print(1._1)` works in luau, but not in darklua & full-moon.
![image](https://github.com/seaofvoices/darklua/assets/55368789/c2d57da1-907e-44c0-be48-ed96720aad15)

**Comment by jeparlefrancais** [comment]
The `unable to convert number` part tells me that full-moon parses it fine, it fails on this project side. Thank you for taking the time to validate these corner cases 👍 If you see test cases missing in [this part of this file](https://github.com/seaofvoices/darklua/blob/main/src/nodes/expressions/number.rs#L580) send them my way and I can add them when I fix this issue.
