### ISSUE TITLE
Cannot add bundle to darklua json

### ISSUE THREAD

**Issue by nickk431** [seaofvoices/darklua#108]
`{
  bundle: {
    "require-mode": "path",
    // by default, darklua will use the following value
    "modules-identifier": "__DARKLUA_BUNDLE_MODULES",
  },
}`

Is on the website which means it should work. But when I try to process a file I get this error.
1 error happened:
-> invalid configuration file at `.darklua.json` (unknown field `bundle`, expected `rules` or `generator`)

**Comment by nickk431** [comment]
I realized that the website was updated while the build with bundle support wasnt released. It works when built from the source.

**Comment by jeparlefrancais** [comment]
You are correct, sorry for this inconvenience! The site is automatically published on each commit, so that is why you are seeing it even if it has not been released yet 😅 

Thanks for giving it a shot already, feel free to open issues if you find anything 🙂
