### ISSUE TITLE
thread 'main' has overflowed its stack.

### ISSUE THREAD

**Issue by christopher-buss** [seaofvoices/darklua#125]
I've attached a file in @jeparlefrancais's discord direct messages due to the agreements made by work for a file that is causing this issue.

Of our 200+ files, this is the only one causing us not to be able to compile due to a stack error.

**Comment by jeparlefrancais** [comment]
Someone reported another case of this error with ProfileService: https://github.com/MadStudioRoblox/ProfileService/blob/master/ProfileService.lua

With this file, it's the full-moon parsing step that overflows. I'm hoping that the parser re-write https://github.com/Kampfkarren/full-moon/pull/276 fixes these kind of issues.

**Comment by nightcycle** [comment]
Heya! Any update on this! I've found it happens pretty regularly when a script gets too long
