### ISSUE TITLE
`remove_unused_variable` trips up on repeat ... until ... when variable defined in loop body is referenced in condition

### ISSUE THREAD

**Issue by sircfenner** [seaofvoices/darklua#186]
Current behavior, when running `darklua process` with `remove_unused_variable` as the only rule:
```Lua
repeat
	local x = true
until x
```
generates:
```Lua
repeat
until x
```
Expected behavior is that variables defined in the loop body are considered "used" if referenced in the condition.
Tested on darklua version 0.13.0.

**Comment by jeparlefrancais** [comment]
Thank you for the report, I'll add this test case once I fix it. I really messed up that rule apparently 😅 

Related to #182
