### ISSUE TITLE
`remove_unused_variable` removes unrelated code in some circumstances

### ISSUE THREAD

**Issue by sircfenner** [seaofvoices/darklua#187]
Haven't figured out the exact pattern of this but created minimal repros of a couple of problem cases.

Current behavior, when running `darklua process` with `remove_unused_variable` as the only rule:

Case 1
```Lua
local x
local y
sideEffects()
```
generates:
```
<empty file>
```
The call to `sideEffects()` should be preserved.

Case 2
```
sideEffects()
local x
sideEffects()
```
generates:
```
<empty lines>
sideEffects()
```
The additional call to `sideEffects()` should be preserved.

Tested on darklua version 0.13.0.

**Comment by jeparlefrancais** [comment]
Thank you for the report, I'll add these test cases too. I really really messed up that rule apparently 😅 

Related to #182
