### ISSUE TITLE
Processing a file with a large do block causes an error

### ISSUE THREAD

**Issue by ewd3v** [seaofvoices/darklua#188]
When I was processing a file with a large do block in it, and got a "thread 'main' has overflowed its stack" error.
While not a big issue I think it's still worth mentioning.

This happened even without any rules enabled (on any generator).
While I couldn't find the exact culprit when I tried recreating the issue, I can still provide [the file](https://github.com/seaofvoices/darklua/files/15081321/code.zip) that caused the error.
Simply removing the do block resolves the issue.

I've only tested this on the darklua version [0.13.0](https://github.com/seaofvoices/darklua/releases/tag/v0.13.0).

**Comment by jeparlefrancais** [comment]
I will close this as it is the same problem as this other issue: https://github.com/seaofvoices/darklua/issues/125

Thank you for taking the time to submit the problematic file, it will be useful once full-moon releases a new version. I'll be able to add this as a test case 🙂
