### ISSUE TITLE
Nesting 10 times

### ISSUE THREAD

**Issue by GISOjinga** [seaofvoices/darklua#190]
If statements nested more than 9 times prevents replication 

https://github.com/seaofvoices/darklua/assets/103523730/476cc851-afea-4db2-91ac-c95b49fab2cc

**Comment by jeparlefrancais** [comment]
I'll close this as it should be resolved by https://github.com/seaofvoices/darklua/pull/219 and available in the next darklua version (that will be 0.14.0)
