### ISSUE TITLE
feat: `remove_dead_function`

### ISSUE THREAD

**Issue by Stefanuk12** [seaofvoices/darklua#191]
To improve DX, a developer may make a function like this:
```lua
local function DebugPrint(...)
    if _G.DEBUG then
        print(...)
    end
end
```

When combined with `remove_unused_if_branch`, `compute_expression`, and `inject_global_value`, it can make writing debug prints and similar code a lot simpler.

---

```lua
local function DebugPrint(...)
    if _G.DEBUG then
        print(...)
    end
end

local function OtherFunction()
    -- actual code here
end


DebugPrint("a debug print here")
OtherFunction()
```
would bundle down to
```lua
local function OtherFunction()
    -- actual code here
end

OtherFunction()
```

---

This is related to #5, this needs to be done first before this can be achieved to have more robust variable tracking.

**Comment by jeparlefrancais** [comment]
Thanks for taking the time to submit this issue! I will link it to this other issue: https://github.com/seaofvoices/darklua/issues/44

It is a trivial sub-case of constant function inlining, where the function is simply empty 😄 It is not _really_ a duplicate but I'll still close it as it will get done using the same rule. I'll add a comment to the issue to remember to support that use case!
