### ISSUE TITLE
Process File from string into string

### ISSUE THREAD

**Issue by Bobrokus** [seaofvoices/darklua#198]
It would be super useful to have the ability to process source code from a string into a string.

I plan on using this library in my project and need to process source code as a string. Reading the source code I've so far only found that it's only possible to process a file at a path.

I believe there must be code for processing string, but I haven't found it yet. I'll be looking further but I'm worried it'll be private. I might try to implement this myself if I don't find anything.

**Comment by Bobrokus** [comment]
Ok. I did find a way to minify code from String:
```rust
pub fn minify(code: &str) -> anyhow::Result<String> {
    let mut generator = darklua_core::generator::DenseLuaGenerator::new(80);

    let parser = Parser::default();

    let block = parser
        .parse(code)
        .map_err(|parser_err| anyhow!(parser_err))?;

    generator.write_block(&block);
    let lua_code = generator.into_string();

    Ok(lua_code)
}

```

**Comment by jeparlefrancais** [comment]
It seems like you've found what you needed so I'll close this issue 🙂
