### ISSUE TITLE
Mention minification functionality on docs

### ISSUE THREAD

**Issue by tomodachi94** [seaofvoices/darklua#99]
Currently, I can't find any mention of minification on the documentation. I think if this was functionality was advertised a little bit more, usage would skyrocket.

**Comment by Sleitnick** [comment]
Looks like it's mentioned in the first page on the docs: https://darklua.com/docs/getting-started/

**Comment by jeparlefrancais** [comment]
Thank you for the feedback, I'll keep that in mind next time I do a pass on the docs site as it could apparently be clearer. I could add a note on the home page.
